# Generated by Django 4.2.10 on 2024-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
    ]
