# Generated by Django 4.2.10 on 2024-03-06 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_order_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_pickup',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 6, 18, 1, 22, 94465)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 6, 18, 1, 22, 94440)),
        ),
    ]
