# Generated by Django 4.2.10 on 2024-03-06 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_order_pickup_alter_order_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_order', to='api.order'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_restaurant', to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_pickup',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 6, 19, 12, 10, 280235)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 6, 19, 12, 10, 280208)),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_restaurant', to='api.restaurant'),
        ),
    ]
