# Generated by Django 4.2.10 on 2024-03-06 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_menu_order_alter_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_pickup',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
