# Generated by Django 4.2.10 on 2024-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_order_order_pickup_alter_order_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(related_name='menu', to='api.menu'),
        ),
    ]
