# Generated by Django 4.2.10 on 2024-03-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_menu_order_order_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Order in progress', 'Order in progress'), ('Ready for pickup', 'Ready for pickup'), ('Order completed', 'Order completed')], default='Order placed', max_length=20),
        ),
    ]
