# Generated by Django 4.2.11 on 2024-03-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_customer_customers_rename_menu_menuitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='item_image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rest_image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/2048px-No_image_available.svg.png'),
        ),
    ]
