# Generated by Django 4.2.11 on 2024-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_menuitems_item_image_restaurants_rest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='manager_pass',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rest_close',
            field=models.TimeField(default='21:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='rest_open',
            field=models.TimeField(default='11:00'),
        ),
    ]
