# Generated by Django 4.2.11 on 2024-03-29 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_restaurants_rest_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_customer', to='api.customers')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_restaurant', to='api.restaurants')),
            ],
        ),
    ]
