# Generated by Django 4.2.11 on 2024-04-03 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_reviews_rating_reviews_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_pickup',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 20, 35, 14, 401500)),
        ),
    ]
