# Generated by Django 4.2.11 on 2024-04-03 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_orders_order_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_pickup',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
